### ISSUE TITLE
Add version update to workflow

### ISSUE THREAD

**Issue by jhollway** [globalgov/qCreate#10]
Problem: at the moment, the `pushrelease.yml `workflow, upon merging a PR, picks up the last tag released, increments it, and then attaches built versions of the package to this tag/release. The problem is, the `pushrelease.yml` workflow only increments the tag, not the `DESCRIPTION` file; we need to manually increment the package's actual `DESCRIPTION` file ourselves. This is not only tiresome, but it could easily lead to discrepancies between the supposed release version and the version number shown when the package is installed.

Some potential solutions to run in the `pushrelease.yml` file:
- [ ] https://github.com/r-lib/desc#normalizing-description-files
- [ ] https://rdrr.io/cran/Orcs/man/bumpVersion.html

**Comment by henriquesposito** [comment]
desc::desc_bump_version() should work here. Though, in this case, we must make sure description file has not been already updated in the PR process and that we can identify whether PR is a patch, minor or major increment.

**Comment by jhollway** [comment]
There's something to be said to making this manual then, also if/once on CRAN
