### ISSUE TITLE
Testing `export_data()` and `import_data()` functions

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#13]
Currently these functions are not being tested. The idea was to create a temporary environment to test them and them erase it afterwards. This would be done with the `create_local_package()` function (commented out in their test scripts), but it is not currently working.

**Comment by henriquesposito** [comment]
This is not anymore a big issue since we split the packages in two. However, this will still be addressed as testing is still important for qCreate.

**Comment by henriquesposito** [comment]
I have been playing around with this for the last couple of hours and, although I can build and delete a test package within for testing, certain document templates are imported to the testthat folder and not deleted afterwards (because of how setup_package() works with qTemplates, some portions are interactive and others are automatic).

At this point I suggest we stop trying to really test export_data(), import_data() and setup_packages() and only test warnings as we currently do because, as I see, this is likely to create more issues and bugs as these functions change. Especially if we do not intend to have qCreate on CRAN.

What do you think @jhollway?

**Comment by jhollway** [comment]
Sounds good.
