### ISSUE TITLE
Decrease the number of false duplicates generated by code_agreements()

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qCreate#24]
`code agreements()` sometimes returns different treaties as duplicates. See the example below:

[https://app.zenhub.com/files/365543800/7193aa26-cf12-4d28-afd7-1e1abbeae477/download](https://app.zenhub.com/files/365543800/7193aa26-cf12-4d28-afd7-1e1abbeae477/download)

**Comment by henriquesposito** [comment]
Thank you for the attaching the summary document, I will think of ways to get at some of the differences overseen.

**Comment by EstherPeev** [comment]
To help thinking of the best solution to differentiate the treaties, I have added some examples of false duplicates generated by `code_agreements()` in the list below: 

[https://app.zenhub.com/files/365543800/983d8786-b7ed-41ca-b0df-d1e2dd0e57d0/download](https://app.zenhub.com/files/365543800/983d8786-b7ed-41ca-b0df-d1e2dd0e57d0/download)

**Comment by henriquesposito** [comment]
Thank you for all the helpful examples @EstherPeev ! I added a code_issues() helper function to help with disambiguating date duplicates. The data list and abbreviations for issues need to be expanded as you will see, but it is one way of dealing with this bug in a more systematic fashion.

**Comment by EstherPeev** [comment]
The new helper function, renamed `code_action()` allowed to drastically reduce the number of false duplicates (from 280 to 54). 
However, it is also generating around 50 qIDs as NAs. I am working on that, but if you have any ideas of where it comes from, @henriquesposito, please let me know.

**Comment by henriquesposito** [comment]
@EstherPeev Yes, I left NAs as returns when code_actons() found duplicates but not matched words for actions. This is to facilitate identification of which agreements are viewed as duplicates but we have not been able to find actions for.
