### ISSUE TITLE
Improve code_type() for better recognizing different type of treaty (exchange of notes, protocol, etc)

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qCreate#26]

**Comment by henriquesposito** [comment]
Also some of the types we have currently are rarely present in most of the datasets. Do you think we really need all the other types or could we just have other (O) for titles that are not amendments, protocol or agreements?

**Comment by EstherPeev** [comment]
What I have seen is that all the other types (so other than Agreement, Protocol and Amendment) are rarely present in dataset. Only 7 out of 3666 in IEADB, but around 85 out of 2733 in GNEVAR. 

I think we can put others than A, P, E under O = Other.

**Comment by henriquesposito** [comment]
I think that is a good suggestion!

@jhollway What do you think about coding agreement types different than agreements, protocols and amendments as others (O)? Thank you.

**Comment by jhollway** [comment]
We can discuss this next meeting, but let's be clear about the coding alternatives:
1) subsume them into e.g. Agreements. This could be useful if we still want to incorporate them into lineages.
2) mark them as NA. This could be useful if we don't want to dilute or bias category codings, but also don't want a catch-all Other/Miscellaneous category

**Comment by henriquesposito** [comment]
Type categories have been changed. Now N stands for notes and minutes (discriptive). S stands for memorandum and strategies (future plans/intentions). R stands for resolutions and declarations (law/policies).

The function for code_types() has also been re-worked to increase accuracy in matching. Now it takes first type coded from title in order as the type of agreement.
