### ISSUE TITLE
Return lists of words and codes used in some of the code_agreements() functions for transparency

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#31]
Some functions in code_agreements() use internal data to return coded letters or abbreviations. However, this data is not easily accessible to users who would like to know where those codes come from and what they mean.

**Comment by henriquesposito** [comment]
The following functions have already been altered to do so in the latest pushes: code_actions(), code_known_agreements() and code_type(). That is, if you run these functions without an argument, the codes and words used to generate a qID are printed in console. This allows users to more easily access information they may want to know.

This will also be implemented for code_parties() and, maybe, code_linkages() for words removed to identify duplicates.

Now the printing of some of these lists in console needs to be adjusted, especially for code_known_agreements(). @EstherPeev do you mind taking a look at this when you have some time and try to make the tables returned prettier in this case? Thank you.

**Comment by EstherPeev** [comment]
I have reworked the output of `code_action()`, `code_type()`, and `code_known_agreements()` but I used different options for each of them. Could you please run the 3 of them @henriquesposito and let me know which output format you prefer? And then I can implement this option for the other functions. 

As you will see, for `code_action()`, and `code_type()`, the output is displayed in the console. For `code_known_agreements()`, the output is displayed in the viewer tab. Also, for `code_action()`, I have added another option that I have commented out if you want to try it as well. 

I personally prefer when the output is displayed in the viewer but I don't know if that is what you originally wanted. Also, I think it could be a useful thing to implement for the other functions you mentioned above (`code_parties()` and `code_linkages()`)

**Comment by henriquesposito** [comment]
Thank you very much @EstherPeev !

I took a look at all of them and, though, many of the printouts look great, some would add unnecessary package dependencies. However, we do have knitr as a suggested package already and I think we can indeed use it for printing in console nicer than the print function. It is not perfect, but a good compromise. 

Thank you once again!
