### ISSUE TITLE
Decrease number of false negatives with code_agreements()

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#32]
Now that we dealt (for the time being) with false positives in code_agreements(), we should try and focus on what we are still missing...

With the new changes to the function, @EstherPeev could you create a list/table of some of the false negatives we are still getting? Thank you.

**Comment by EstherPeev** [comment]
@henriquesposito Here is the list of false negatives found with the new version of `code_agreements()`:

[https://app.zenhub.com/files/365543800/6b87c08d-3f5f-4ae4-95a0-0b7f7b67e6fa/download](https://app.zenhub.com/files/365543800/6b87c08d-3f5f-4ae4-95a0-0b7f7b67e6fa/download)

There are few cases that were already mentioned in the last list I have made (mostly those with an additional word like **Basin, Resources, Priority**, etc). 

The majority of them are multilateral and they differ in the acronym part. `code_acronym()` adjustments could therefore resolve many of the cases described in the list.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev, this is very helpful!

I saw also that you solved some of the issues with punctuation, region naming and special characters in your last push for standardise_dates(). Thank you for that. 

Based on the document, I also made some changes to code_agreements(). Now, code_acronym() removes some of the differentiating words identified that are not consistent across datasets as well as some agreement cities (or abbreviations) that appear inconsistently through the titles across datasets. However, this implies we will have to updated every now and them the list of words once we see these issues appear, as we have been doing for standardise_titles(). We also need to be careful not to remove important information and, thus, why we may have to update the list of words manually.

@EstherPeev , could you provide, once more, a new list of false negatives so we can keep on updating code_agreements() to increase accuracy? Thank you.

**Comment by EstherPeev** [comment]
So it seems that there are very few false negatives left as you can see @henriquesposito from the list below: 

[https://app.zenhub.com/files/365543800/33949710-8d35-4433-9ebe-9124cb74cd49/download](https://app.zenhub.com/files/365543800/33949710-8d35-4433-9ebe-9124cb74cd49/download)

There are some cases not listed here that I have directly solved through `standardise_titles()` and `code_acronym()` because it was minor changes (adding some cities name to ignore or write "Decision-Making" in a consistent way for example). 

For the rest, I think it can be solved easily but would require some consensus on how we treat them (e.g. do we identify Adjustment as Amendment? Do we make `code_acronym()` ignore "Fao", "Sphere", "Field", "Council", "Commission" as well?)

**Comment by henriquesposito** [comment]
Thank you @EstherPeev , very helpful once again!

I fixed the issue with the year. It was not the year that was counting as a letter, but the braces. So I removed the braces from the world count in `code_parties()`.

I added field and sphere as differentiating words to be removed as these do not contain much new information and appear inconsistently across some titles/datasets.

I fixed the issue with the special character by just removing it without subbing it for spaces.

I fixed the fisheries issue. If title starts with word fisheries, code_acronym() removes the word only if it is present at the beginning of the title. @EstherPeev Could you please try and check if there are other differentiating words that appear at the beginning of agreement titles that cause acronyms to be different and add these to the function as well? Thank you.

**Comment by EstherPeev** [comment]
Thanks for all of this @henriquesposito 

So I have updated `code_agreements()` with minor changes according to few words or punctuations generating false negatives:

* I have deleted the words "Fisheries" (only when the title starts with it) and "Text" in `code_parties()`. The different qIDs were not only generated by `code_acronym()`, but also in the number of words added in `code_parties()`. 

* I have also added "about" in the list of predictable words and "Kyoto" in the list of the cities `code_acronym()` should ignore. 

* The space left before the parenthesis deleted from `code_parties()` was adding one word to the title so I have deleted it as well.

The only case left of false negative that I was able to detect is

![Capture d’écran 2021-07-01 à 16.17.15.png](https://images.zenhubusercontent.com/5ff2de14fb5a58fc49c60af6/8db5b7e5-9bcd-416a-95be-149cb6cce547)

It would require to delete also the word "East" from the `code_acronym()`. 

Apart from that I think we are done with the false negatives, it looks pretty good from what I have been able to check in IEADB, ECOLEX and GNEVAR.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev . Let's leave this one as is, these are not technically the same region and we should not delete an important word a East to generate acronym. 

However this could serve as a reference for when we write methods for "consolidating" non-matching qIDs. For example, if year is the same and at least 4 digits are the same, maybe we look to see if titles are very similar and, if so, ask users if these are the same agreement or not.
