### ISSUE TITLE
Decide if the new version of `standardise_dates()` will be used or dates will be dealt with in other ways

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#33]
A new version of the `standardise_dates()` function that returns character ranges for uncertain dates and deals with negative and future dates has been awaiting deployment in a separate branch for awhile now. The reason being that we needed to implement a `resolve_dates()` function first, which has been created. 

Now that the packages were split and the resolve functions are in the develop branch of qData (even if commented out), should we move ahead with `standardise_dates()`? 

There are also ways in which a new date class and printing methods can be written for dates and used, though this might entail re-working `standardise_dates()` in a different direction. Even so, I still believe resolve functions will need to be used if users are to be given a choice about which dates they would like to use and for mathematical operations be possible for ranges. 

What do you think @jhollway ?

**Comment by jhollway** [comment]
I have started working on the new date class, which I think will solve some problems, and create new required changes.
