### ISSUE TITLE
Decrease number of false positives with code_agreements()

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qCreate#34]
With the new version of `code_agreements()`, the number of false positives evolved again. I think there are few of them on which we can work on to reduce their number. Here is a list of them: 

[https://app.zenhub.com/files/365543800/76306408-341e-4ffb-acbd-fae2460501d6/download](https://app.zenhub.com/files/365543800/76306408-341e-4ffb-acbd-fae2460501d6/download)

Most of them are linked to `code_parties()`, either because the states are not detected correctly or because the number of words are the same. Maybe for the latter case, some of the words contained only in one of the title (e.g. Plants) could be ignored by `code_parties()` like this the two titles would have different number of words which would differentiate them.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev for identifying the issues and pointing at possible solutions!

**Comment by EstherPeev** [comment]
There are few false positives left with the new version of the function, thanks to the changes you made @henriquesposito. Here is the list of those remaining:

[https://app.zenhub.com/files/365543800/56b0d46b-b933-4061-894d-c4ad6bbb489c/download](https://app.zenhub.com/files/365543800/56b0d46b-b933-4061-894d-c4ad6bbb489c/download)

Some are only one word difference. I think a part of them could be solved simply by adding one word to ignore when `code_parties()` counts the total of words. For others, I think it will have to go to the future helper function of `consolidate()`, which will be used to solve that kind of conflict (like the second case presented in the list where there is no word difference)

**Comment by henriquesposito** [comment]
Thank you @EstherPeev ! The main issue here was addressed, which was the bug with linkages returning for treaties types that are not agreements. 

For the issue of false positives for bilateral treaties, a new approach will be tried with coding the activity of the treaties with the code_activities() function.
