### ISSUE TITLE
Fix website deployment issues with qCreate

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#36]
The qCreate pkgdown page is not currently working. It appears it is not properly being deployed and, thus, the link does not appear on the GitHub page for the package.

**Comment by EstherPeev** [comment]
So I checked and the qCreate website is building correctly locally. It might be a problem in the settings of the repo page on Github but I don't have access to it. Do you have any other idea @henriquesposito of where it could come from?
