### ISSUE TITLE
Update templates for database documentation generated by export_data()

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qCreate#43]
Replace qData by qCreate

**Comment by henriquesposito** [comment]
For documentation for databases, please replace qData/qCreate by the new qPackage name.

For some of the calls for package functions in scripts (i.e. preparation) need be updated as well. 

There is also a reference to qData in the pushrelease file that needs to be changed to the qPackage name if possible.

Thank you!

**Comment by EstherPeev** [comment]
So I have added one argument to `export_data()`, which allows to generate the database documentation file named by the name of the qPackage. 

`export_data()` should be run as follows:

```{r}
export_data(IEADB, database = "agreements", package = "qEnviron")
```

I have also changed the dataset script preparation by replacing qData by qCreate
