### ISSUE TITLE
Create an `update_packages()` function that updates qPackages

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#6]
Whenever qData changes templates, file structure or tests, qPackage contributors have to re-run `setup_package()` to update for these. Though, this is risk and can cause some files and/or changes to be lost. Create an `update_packages()` function that updates for changes in qPackages without  having to re-run `setup_packages()`.

**Comment by henriquesposito** [comment]
A first version of the function was added. It currently automatically updates some files as PR and bug report templates while asks users to indicate if license, code of conduct and contributing files should also be updated.

**Comment by jhollway** [comment]
Ok, and if a user answers that they should, they are simply overwritten? And what happens with any e.g. DESCRIPTION file updates?

**Comment by henriquesposito** [comment]
Yes, the files are overwritten if yes. 

As for other files, as description, tests and documentation I do not know if there is a way of updating these without overwriting users' inputs. That is, all of the files where users are likely to have manually worked on remain the same, for now, while other files as PR templates are overwritten (along with License and COC if users choose to do so).

**Comment by jhollway** [comment]
Tests will update automatically any time contributors re-`export_data()`. Documentation they will probably have to manage themselves for now. But maybe the `{DESC}` package (or our own `add_author()`) offer some suggestions about how to manage this?

**Comment by henriquesposito** [comment]
Yes, indeed there might be ways in which certain sections of the description file can be updated looking at the `DESC` package and our add_author() function. The challenge here is to know what should be updated and not. I will look into this and try to keep author's names and information while updating the bottom half (dependencies, suggestions and so on) of the description file if author's choose to do so.
