### ISSUE TITLE
Research best way to store data for codes for agreements function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#8]
Some options are creating a new GitHub repo or a sql file. The requirements are that it writes and reads in the new `code_agreements()` function as well as that it allows for manual overwriting.

**Comment by henriquesposito** [comment]
As of now, we have several data lists included in qCreate. I assume that these will be the templates for storing online data for code_agreements(). I believe that either a SQL database or GitHub repo/package would work for these purposes. Although there could be costs associated with having more than one or a large SQL database online. 

The challenge I see, and I am yet to propose a solution, is getting these lists to update more automatically when users use code_agreements(). As I see, the SQL or GitHub approaches are equivalent if we decide to upload these lists and manually update every now and then.

**Comment by henriquesposito** [comment]
I have created a repository called qList and added a large dataset that combines the names of environmental agreements in Gnevar, Ecolex and IEADB. 

After tweaking code_agreements() to increase accuracy in finding duplicates and removing all row duplicates, there are still two main issues left. First, there are several title duplicates that have different dates across datasets and, thus, different qID. Second, some datasets are more complete than others and qIDs are returned with linkages and actions and, thus, an extended version of qID which does not match title and date duplicates from different datasets. 

I will keep on working out ways to clean and wrangle this list of agreements. This issue also relates to some of the concerns raised about collapse()/concentrate() functions. Once some solutions are developed and applied, then code_agreements() can look up the repository for title and date duplicates to assign a qIDs in more consistent ways across datasets allowing comparisons.

**Comment by jhollway** [comment]
Putting a pin in this as current approach is different
